#!/bin/bash

echo "🔍 Checking Supabase Database Setup"
echo "===================================="
echo ""
echo "Please verify the following in your Supabase Dashboard:"
echo ""
echo "1. Go to https://supabase.com/dashboard"
echo "2. Select your 'clinroute' project"
echo "3. Go to 'Table Editor' in the left sidebar"
echo "4. Check if 'profiles' table exists"
echo ""
echo "If the profiles table doesn't exist:"
echo "  → Go to 'SQL Editor'"
echo "  → Copy the contents of sql/supabase-setup.sql"
echo "  → Paste and run it to create the table"
echo ""
echo "5. If the table exists, verify it has these columns:"
echo "   - id (uuid, primary key)"
echo "   - email (text)"
echo "   - role (text)"
echo "   - name (text)"
echo "   - phone (text)"
echo "   - profile_complete (bool)"
echo "   - family_members (jsonb)"
echo ""
echo "6. Check Row Level Security (RLS) policies:"
echo "   → Go to 'Authentication' > 'Policies'"
echo "   → The 'profiles' table should have 4 policies:"
echo "     • Users can view their own profile (SELECT)"
echo "     • Users can insert their own profile (INSERT)"
echo "     • Users can update their own profile (UPDATE)"
echo "     • Users can delete their own profile (DELETE)"
echo ""
echo "📝 Common Issues:"
echo "  - Missing profiles table → Run sql/supabase-setup.sql"
echo "  - RLS blocking inserts → Check policies allow INSERT where auth.uid() = id"
echo "  - Wrong column types → Re-run setup script"
echo ""
echo "After fixing, try logging in again."
echo ""
