#!/bin/bash

echo "🔧 Clearing Browser Local Storage Locks"
echo "========================================"
echo ""
echo "⚠️  This script will help you clear stuck auth locks."
echo ""
echo "To fix the login issue, please follow these steps:"
echo ""
echo "1. Open your browser (Chrome/Firefox/Edge)"
echo "2. Press F12 to open Developer Tools"
echo "3. Go to the 'Console' tab"
echo "4. Copy and paste this command:"
echo ""
echo "────────────────────────────────────────"
echo "Object.keys(localStorage).forEach(key => { if(key.includes('lock') || key.includes('clinroute-auth')) { console.log('Removing:', key); localStorage.removeItem(key); }}); location.reload();"
echo "────────────────────────────────────────"
echo ""
echo "5. Press Enter - this will clear locks and reload the page"
echo "6. Try logging in again"
echo ""
echo "Alternative: Clear all browser data for localhost:3000"
echo "  - Chrome: Settings > Privacy > Clear browsing data > Cookies/Site data"
echo "  - Firefox: Settings > Privacy > Cookies and Site Data > Clear Data"
echo ""
